name    'maxchk-salt'
version '0.0.4'
author  'maxchk'
license 'Apache License, Version 2.0'
summary 'SaltStack module'
description 'Install, configure and manage SaltStack'
project_page 'https://github.com/maxchk/puppet-salt'
